# -*- coding: utf-8 -*-
"""Stats parlacap

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUwhN1PjRnzFtYiw1yxxNo20y8HS_fvF
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

# Chargement du fichier
file_path = "/content/drive/MyDrive/M1 IDL/parlacap.tsv"
print(" Lecture du fichier en cours...")
df = pd.read_csv(file_path, sep='\t')

# Calcul du nombre de mots pour le dataset brut
df['word_count'] = df['text'].astype(str).apply(lambda x: len(x.split()))

print("\n--- STATISTIQUES AVANT NETTOYAGE ---")
print(f"🔹 Nombre total de discours : {len(df):,}")
print("\n🔹 Lignes corrompues ou vides :")
print(df.isnull().sum())
print("\n🔹 Répartition par parti (en %) :")
print((df['speaker_party'].value_counts(normalize=True) * 100).round(2))
print(f"\n🔹 Longueur des discours (médiane) : {df['word_count'].median():.0f} mots")

# ==========================================
#                  NETTOYAGE
# ==========================================

# Filtre sur les labels pour enlever les "-" ou les vides
df_clean = df[(df['speaker_party'] != "-") & (df['speaker_party'].notnull())].copy()

# Filtre sur les discours de moins de 15 mots
df_clean = df_clean[df_clean['word_count'] > 15]

# Groupement des partis de fréquence trop basse (<5%)
threshold = 5.0
counts_pct = df_clean['speaker_party'].value_counts(normalize=True) * 100
petits_partis = counts_pct[counts_pct < threshold].index
df_clean['party_grouped'] = df_clean['speaker_party'].replace(petits_partis, 'AUTRE')

# ==========================================
#       STATISTIQUES APRÈS NETTOYAGE
# ==========================================

print("\n--- STATISTIQUES APRÈS NETTOYAGE ---")

# Répartition des classes après regroupement
print("\n🔹 Nouvelle répartition par parti (en %) :")
new_repartition = df_clean['party_grouped'].value_counts(normalize=True) * 100
print(new_repartition.round(2))

# Statistiques de longueur après nettoyage
print("\n🔹 Nouvelle longueur des discours (en mots) :")
print(f"   - Moyenne : {df_clean['word_count'].mean():.0f} mots")
print(f"   - Médiane : {df_clean['word_count'].median():.0f} mots")
print(f"   - Minimum : {df_clean['word_count'].min()} mots")
print(f"   - Maximum : {df_clean['word_count'].max()} mots")

# Résumé de la purge
print(f"\n🔹 Bilan du nettoyage :")
print(f"   - Lignes conservées : {len(df_clean):,}")
print(f"   - Lignes supprimées : {len(df) - len(df_clean):,}")
print(f"   - Pourcentage de données conservées : {(len(df_clean)/len(df)*100):.1f}%")

# Estimation du nombre de tokens
df_clean['estimated_tokens'] = df_clean['word_count'] * 1.3

# Calcul du pourcentage de textes qui dépassent la limite de 512 tokens
too_long = df_clean[df_clean['estimated_tokens'] > 512]
percentage_truncated = (len(too_long) / len(df_clean)) * 100

print(f"\n --- ANALYSE DE LA TRONCATURE --- ")
print(f"🔹 Discours dépassant la limite (512 tokens) : {len(too_long):,}")
print(f"🔹 Pourcentage de données tronquées : {percentage_truncated:.2f}%")

if percentage_truncated > 10:
    print("Le dataset a beaucoup de discours longs. Le modèle ne lira que le début")
else:
    print("Perte d'informations faible")