# -*- coding: utf-8 -*-
"""ProjetPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14N8o8VmSWESJYuWl2-F15OBGcY8eUdAy
"""


from transformers import AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments, DataCollatorWithPadding
from datasets import load_dataset
import evaluate
import numpy as np

#fonction d'évaluation(les métriques)
accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    return {
        "accuracy": accuracy.compute(predictions=predictions, references=labels)["accuracy"],
        "f1_macro": f1.compute(predictions=predictions, references=labels, average="macro")["f1"]
    }
#charger le fichier
dataset = load_dataset("csv", data_files="parlacap.tsv", sep="\t", split="train")
dataset = dataset.filter(lambda x: x["speaker_party"] is not None and x["speaker_party"] != "-")

#nettoyage des données
min_words = 15
dataset = dataset.filter(lambda x: len(x["text"].split()) > min_words) #pour filtrer les prises de parole trop courtes

#labéliser les données
dataset = dataset.class_encode_column("speaker_party")
dataset = dataset.rename_column("speaker_party", "label")

# On réserve  20% des données pour le test
dataset_split = dataset.train_test_split(test_size=0.2, seed=42)

#choix du modèle
model_name = "cmarkea/distilcamembert-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

#tokenisation
def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True)

tokenized_data = dataset_split.map(preprocess_function, batched=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# Dictionnaire/table de correspondance (le modèle ne comprend pas le texte)
label_names = dataset.features["label"].names

id2label = {i: label_names[i] for i in range(len(label_names))}
label2id = {label_names[i]: i for i in range(len(label_names))}

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(label_names),
    id2label=id2label,
    label2id=label2id
)

#entrainement du modèle
training_args = TrainingArguments(
    output_dir="output",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    push_to_hub=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_data["train"],
    eval_dataset=tokenized_data["test"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()